### ISSUE TITLE
Cytoscape is shutdown

### ISSUE THREAD

**Issue by rafikg** [BaderLab/cy3d-impl#14]
I installed Cytoscape and cy3d on ubuntu 20.04. When I try to cread a 3d view, the program shutdown and I get this error.
```
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```
 
java -version command:
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
``` 
echo $JAVA_HOME:
```
/usr/lib/jvm/java-11-openjdk-amd64

```

**Comment by ariadnavillam** [comment]
I found a solution here https://github.com/MovingBlocks/Terasology/issues/4155. The problem is suppose to be with OpenJDK.

**Comment by mikekucera** [comment]
Sorry, but cy3d is no longer in active development. Over time the library that cy3d uses to interface with OpenGL will become more and more out of date, leading to cy3d failing on more platforms.
