### ISSUE TITLE
Z Location Style is not reflected in Cy3D network view(?)

### ISSUE THREAD

**Issue by kozo2** [BaderLab/cy3d-impl#7]
I tried to layout Z Location with some node attribute.
But it seems those are not reflected to Cy3D network view.

How can I set the 3D node layout with `Style in Control Panel tab`?

![image](https://user-images.githubusercontent.com/12192/53059242-7b33bc80-34f9-11e9-8ade-79a01409ac5d.png)

**Comment by mikekucera** [comment]
Hi Kozo,

I just tested this and it seems to work. Now if you run a layout after setting the mapping in the style panel the layout will override the mapping. You will need to re-apply the visual style to set the z location again.

**Comment by kozo2** [comment]
@mikekucera Thank you for your comment, I'll check.

**Comment by kozo2** [comment]
@mikekucera I'm sorry. I was wrong. The Z location vizmap worked well for galFiltered.cys.
Here I mapped *Stress* column to Z location with Passthrough Mapping.
The Z location changed certainly.
![image](https://user-images.githubusercontent.com/12192/54398166-58618600-46fc-11e9-8d33-4a22444be1af.png)

**Comment by mikekucera** [comment]
Hi Kozo,

No worries, Thanks for testing it.
