### ISSUE TITLE
Moderately sized network freezes when labels are rendered

### ISSUE THREAD

**Issue by Digital-ecologist** [BaderLab/cy3d-impl#9]
Hello.  When rendering a moderately sized network (61 nodes and 136 edges), the network will render, rotate, and zoom in and out perfectly, as long as the node labels are not rendered. Clicking the label button in the upper right-hand corner will cause panning, rotating, and zooming to become choppy, and eventually the main view will freeze, although the Birdseye view will not freeze. Turning off the labels will cause the program to unfreeze most of the time, although sometimes cytoscape crashes. I've attempted this on three different Windows machines, with different graphics cards, and watching task manager on two of the machines indicates that it's not overtaxing the graphics card. Also, testing with a tiny network two square nodes with a single edge between them the program never crashes. So it's somehow connected to network size. Your assistance in resolving this freezing issue would be greatly appreciated. Thank you for the excellent work on this 3D visualization tool. I've attached an example session where the bug is repeatable 
[example file.zip](https://github.com/BaderLab/cy3d-impl/files/5086024/example.file.zip)

**Comment by mikekucera** [comment]
Hi @Digital-ecologist 

I have created a build with a fix for this bug. Could you please give it a quick test before I release it to the app store.

The jar file is here: https://github.com/BaderLab/cy3d-impl/releases/tag/1.1.3-RC1
Install it by copying it to your `~/CytoscapeConfiguration/3/apps/installed` folder.

Thanks!

**Comment by Digital-ecologist** [comment]
Thank you so much! The new version of the app seems to have resolved the issue. I've tried it with two different networks on two different laptops, and everything seems to run smoothly.
